# NGINX DEPLOYMENT SERVICE
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-svc
spec:
  selector:
    app: nginx-rtmp-deploy
  ports:
    - name: http
      protocol: TCP
      port: 1935
      targetPort: 1935
  externalIPs:
    - 192.168.0.192
# Here I am using the master node IP
# as externalIPs
