---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-svc
spec:
  selector: 
    app: nginx-nodeport-01
    department: sales
  type: NodePort 
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 2080
      nodePort: 32080
      name: sales-users
    - protocol: TCP
      port: 3043
      targetPort: 2043
      nodePort: 32043
      name: sales-admins
