apiVersion: v1
kind: Service
metadata:
  name: apache-httpd-service
  namespace: ingress-nginx
spec:
  selector:
    app: apache-httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
