# NGINX DEPLOYMENT SERVICE
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
spec:
  selector:
    app: nginx-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.0.144
# Here I am using the master node IP
# as externalIPs
