apiVersion: v1
kind: Service
metadata:
  name: service-02-nginx
  labels:
    app: deploy-service-02-nginx-app
spec:
  type: LoadBalancer
  selector:
    app: deploy-service-02-nginx-app
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-02-nginx
  labels:
    app: deploy-service-02-nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-service-02-nginx-app
  template:
    metadata:
      labels:
        app: deploy-service-02-nginx-app
    spec:
      containers:
      - name: deploy-service-02-nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
#https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/
