apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.30.2.100-172.30.2.200  # Ensure this matches your node's subnet, adjust based on your network . . . Please use the range of the node01 172.30.2.100-172.30.2.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
